# Generated by Django 5.1.3 on 2024-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_freedom', '0002_remove_candidateprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='level',
            field=models.CharField(choices=[('no_experience', 'Без опыта'), ('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='no_experience', max_length=20, verbose_name='Уровень'),
        ),
    ]
