# Generated by Django 5.1.3 on 2024-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_freedom', '0003_alter_candidateprofile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='active_vacancies',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='successful_hires',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Департамент'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], default='other', max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='processed_applications',
            field=models.IntegerField(default=0, verbose_name='Обработано заявок'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='social_networks',
            field=models.JSONField(blank=True, default=dict, verbose_name='Социальные сети'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='successful_applications',
            field=models.IntegerField(default=0, verbose_name='Успешно обработанные заявки'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Регион'),
        ),
    ]
