# Generated by Django 5.1.3 on 2024-11-08 14:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='current_location',
            field=models.JSONField(blank=True, default=dict, verbose_name='Текущее местоположение'),
        ),
        migrations.AddField(
            model_name='application',
            name='desired_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Желаемая зарплата'),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Оценка соответствия'),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки рекрутера'),
        ),
        migrations.AddField(
            model_name='application',
            name='relocation_status',
            field=models.CharField(blank=True, choices=[('ready', 'Готов к переезду'), ('not_ready', 'Не готов к переезду'), ('remote_only', 'Только удаленная работа')], max_length=20, null=True, verbose_name='Готовность к переезду'),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[('website', 'Сайт компании'), ('recommendation', 'Рекомендация'), ('search', 'Поиск в базе'), ('other', 'Другое')], default='website', max_length=20, verbose_name='Источник отклика'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='country',
            field=models.CharField(default='Казахстан', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department',
            field=models.CharField(default='', max_length=100, verbose_name='Департамент'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='desired_experience',
            field=models.IntegerField(default=0, verbose_name='Требуемый опыт работы (лет)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='desired_level',
            field=models.CharField(choices=[('no_experience', 'Без опыта'), ('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20, verbose_name='Требуемый уровень'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='desired_specialization',
            field=models.CharField(default='', max_length=100, verbose_name='Требуемая специализация'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contract', 'Контракт'), ('temporary', 'Временная'), ('remote', 'Удаленная работа')], default='full_time', max_length=20, verbose_name='Тип занятости'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hard_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Требуемые технические навыки'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='region',
            field=models.CharField(default='', max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(default='', verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальная зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная зарплата'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='soft_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None, verbose_name='Требуемые софт-скиллы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='Технический стек'),
        ),
    ]
