# Generated by Django 5.1.3 on 2024-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_freedom', '0006_alter_candidateprofile_user_and_more'),
        ('recruiting_system', '0002_remove_vacancy_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('interview', 'Назначено собеседование')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'candidate')},
        ),
    ]
