# Generated by Django 5.1.3 on 2024-11-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_freedom', '0005_candidateprofile_work_experience'),
        ('recruiting_system', '0002_remove_vacancy_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('specialization_score', models.IntegerField(default=0)),
                ('hard_skills_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('education_score', models.IntegerField(default=0)),
                ('about_me_score', models.IntegerField(default=0)),
                ('soft_skills_score', models.IntegerField(default=0)),
                ('tech_stack_score', models.IntegerField(default=0)),
                ('languages_score', models.IntegerField(default=0)),
                ('level_score', models.IntegerField(default=0)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_analyses', to='auth_freedom.candidateprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_analyses', to='recruiting_system.vacancy')),
            ],
            options={
                'verbose_name': 'Анализ кандидата',
                'verbose_name_plural': 'Анализы кандидатов',
                'ordering': ['-reputation_score', '-match_score'],
            },
        ),
    ]
