# Generated by Django 5.1.3 on 2024-11-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanalysis',
            name='top_strength_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateanalysis',
            name='top_strength_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateanalysis',
            name='top_strength_3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
