# Generated by Django 5.1.3 on 2024-11-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_candidates', '0002_candidateanalysis_top_strength_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanalysis',
            name='candidate_data_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
