# Generated by Django 5.1.3 on 2024-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_candidates', '0003_candidateanalysis_candidate_data_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanalysis',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
