# Generated by Django 5.1.3 on 2024-11-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_freedom', '0005_candidateprofile_work_experience'),
        ('recruiting_system', '0002_remove_vacancy_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='auth_freedom.candidateprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='recruiting_system.vacancy')),
            ],
            options={
                'verbose_name': 'AI Анализ',
                'verbose_name_plural': 'AI Анализы',
                'ordering': ['-match_score'],
            },
        ),
    ]
