# Generated by Django 5.1.3 on 2024-11-09 06:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_freedom', '0005_candidateprofile_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_freedom.recruiterprofile')),
            ],
            options={
                'verbose_name': 'Массовая загрузка',
                'verbose_name_plural': 'Массовые загрузки',
            },
        ),
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('txt', 'TXT')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('converted', 'Конвертировано'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(default=dict)),
                ('extracted_name', models.CharField(blank=True, max_length=200)),
                ('extracted_email', models.EmailField(blank=True, max_length=254)),
                ('extracted_phone', models.CharField(blank=True, max_length=20)),
                ('extracted_experience_years', models.IntegerField(blank=True, null=True)),
                ('extracted_specialization', models.CharField(blank=True, max_length=100)),
                ('extracted_level', models.CharField(blank=True, choices=[('no_experience', 'Без опыта'), ('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=20)),
                ('extracted_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_location', models.JSONField(blank=True, default=dict)),
                ('extracted_tech_stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('extracted_hard_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('extracted_soft_skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('extracted_education', models.JSONField(blank=True, default=dict)),
                ('extracted_work_experience', models.JSONField(blank=True, default=list)),
                ('extracted_languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('bulk_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to='convertor_to_json.bulkupload')),
                ('created_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resume', to='auth_freedom.candidateprofile')),
            ],
            options={
                'verbose_name': 'Файл резюме',
                'verbose_name_plural': 'Файлы резюме',
                'indexes': [models.Index(fields=['status', 'upload_date'], name='convertor_t_status_d803cb_idx'), models.Index(fields=['extracted_email'], name='convertor_t_extract_f17ccb_idx'), models.Index(fields=['extracted_specialization'], name='convertor_t_extract_a6d151_idx')],
            },
        ),
    ]
