# Generated by Django 5.1.3 on 2024-11-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor_to_json', '0002_bulkupload_batch_size_bulkupload_processing_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkupload',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('stopped', 'Остановлено')], default='pending', max_length=20),
        ),
    ]
