# Generated by Django 5.1.3 on 2024-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor_to_json', '0003_alter_bulkupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='current_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
